[package]
name = "zj-sesh"
version = "0.1.0"
authors = ["Luan Santos <zj-sesh@luan.sh>"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
zellij-tile = "0.43.1"
chrono = "0.4.0"
fuzzy-matcher = "0.3.7"
unicode-width = "0.2.1"
humantime = "2.1.0"
uuid = { version = "1.7.0", features = ["v4"] }
